# Generated by Django 4.2 on 2025-09-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategory',
            new_name='OrderStatus',
        ),
    ]
