# Generated by Django 4.2 on 2025-09-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_menucategory_orderstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatus',
            new_name='MenuCategory',
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu Categories'},
        ),
    ]
